# Generated by Django 5.1.1 on 2024-09-18 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodFinder', '0003_rename_department_guests_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='guests',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
        migrations.AddField(
            model_name='guests',
            name='zipcode',
            field=models.CharField(blank=True, default='00000', max_length=10),
        ),
        migrations.AddField(
            model_name='guests',
            name='favorite_restaurants',
            field=models.ManyToManyField(blank=True, to='foodFinder.restaurant'),
        ),
    ]
