# Generated by Django 5.1.1 on 2024-09-30 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodFinder', '0007_remove_guest_zipcode_alter_guest_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favorite_restaurants',
            field=models.ManyToManyField(blank=True, to='foodFinder.restaurant'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
