# Generated by Django 5.1.1 on 2024-10-01 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodFinder', '0009_guest_first_name_guest_last_name_userprofile_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='user',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='user',
            new_name='username',
        ),
    ]
