# Generated by Django 5.1.1 on 2024-10-01 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodFinder', '0010_rename_user_guest_username_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='username',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='username',
            new_name='user',
        ),
    ]
